### PR TITLE
Implement RadioGroup.enableCell()

### PR DESCRIPTION
**Pull request by jenskutilek**

### CODE REVIEW

**Comment by justvanrossum** [comment]
Thanks! Little doc string maybe? Also, I would rename the `cell_index` argument to `index` (like elsewhere in the code).

**Comment by jenskutilek** [comment]
Sure! Is the term "cell" easy to understand in this context though? Cells is what these are called internally, while vanilla calls the NSMatrix "RadioGroup" and the cells "radio buttons".

What could be a better name for the method: "enableRadioButton", "enableOption", ...?

**Comment by justvanrossum** [comment]
Oh, good question! I vote for `enableRadioButton(index)`.

**Comment by jenskutilek** [comment]
OK, done!

**Comment by justvanrossum** [comment]
Thank you, Jens!

**Pull request merged**
