### PR TITLE
adding isVertical

### PR DESCRIPTION
**Pull request by typemytype**
explicitly set the direction of a Slider

see #84

### CODE REVIEW

**Comment by justvanrossum** [comment]
Is this backwards compatible? Does this:

```python
from vanilla import *

w = Window((200, 200))
w.sl1 = Slider((20, 20, 80, 20))
w.sl2 = Slider((20, 50, 20, 80))
w.open()
```
...still give a horizontal slider and a vertical slider?

**Comment by typemytype** [comment]
its not backwards compatible, all sliders are horizontal sliders, only when `isVertical=True` is specified the slider will be vertical.

**Comment by typemytype** [comment]
an other option could be: if the `isVertical` is None it retreives it from the posSize, calculating this value from posSize could be wrong

**Comment by typemytype** [comment]
this should do it

**Comment by justvanrossum** [comment]
Getting this error now with the above snippet:

```
Traceback (most recent call last):
  File "<untitled>", line 4, in <module>
  File "/Users/just/code/git/vanilla/Lib/vanilla/vanillaSlider.py", line 144, in __init__
    self._nsObject.setVertical_(isVertical)
AttributeError: 'VNSSlider' object has no attribute 'setVertical_'
```

**Comment by typemytype** [comment]
os10.10?  

it should be there... https://developer.apple.com/documentation/appkit/nsslider/1527901-vertical?language=objc support from 10.0+...

there was this check on the os version in the older version... I guess I already encountered that bug

but that means `_nsObject.isVertical()` also does not work?

**Comment by typemytype** [comment]
if so that means not way to be explicit... so then I leave it as is, with the bugs

**Comment by justvanrossum** [comment]
Yes, 10.10.

`isVertical()` works, `setVertical_()` doesn't. So I guess it was a read-only property earlier.

**Pull request merged**
