### PR TITLE
Nicer values for the text offset @ "mini"

### PR DESCRIPTION
**Pull request by Mark2Mark**
Can we use these values? They look better to me. With the old values the text was always too tight to the check mark.

### CODE REVIEW

**Comment by Mark2Mark** [comment]
This is how these values look like when changed to my proposals:
small
screen shot 2017-06-27 at 15 18 33

mini
screen shot 2017-06-27 at 15 19 12

**Comment by justvanrossum** [comment]
This may affect other people's layouts, so I'm not sure it's a wise idea to change this.

@typemytype and @typesupply, could you give this a quick look?

**Comment by typemytype** [comment]
test script: https://gist.github.com/typemytype/0ec4f71a11597d5936c8941bff15b6d4
on 10.10: 

screen shot 2017-10-20 at 09 47 47

**Comment by typemytype** [comment]
and this seems to be fixed on 10.12

screen shot 2017-10-20 at 09 50 20

**Comment by typemytype** [comment]
not fixed on 10.11

screen shot 2017-10-20 at 09 56 21

**Comment by typemytype** [comment]
fixed in 10.12

screen shot 2017-10-20 at 10 02 23

**Comment by typemytype** [comment]
I would propose to leave it as it is, so it will not change existing UIs on older OSs

but from 10.12 and higher switch to the standaard NSSwitchButton 

I think the alignment is rather problematic with this request

screen shot 2017-10-20 at 09 47 47

**Comment by justvanrossum** [comment]
Ok, not merging. Thanks!

**Comment by Mark2Mark** [comment]
Good point @justvanrossum and @typemytype 
Didn’t think of that! Thanks for pointing it out and considering. Will use my subclasses where needed.

**Pull request closed without merging**
