### PR TITLE
never do `from AppKit import *`

### PR DESCRIPTION
**Pull request by schriftgestalt**
This reduces the time needed to do `import vanilla` from 3.5s to 0.5s
(one my macBook).

The first time a script calls `from AppKit import *`, it takes several seconds. Subsequent calls will be much faster.

### CODE REVIEW

**Comment by justvanrossum** [comment]
This is indeed dramatic. This seems to be fixed in more recent versions of PyObjC, and/or Python 3:
```
$ python -c "import objc; print(objc.__version__); import time; t = time.time(); from AppKit import *; print(time.time() - t)"
2.5.1
3.76603484154
$ python3 -c "import objc; print(objc.__version__); import time; t = time.time(); from AppKit import *; print(time.time() - t)"
4.0.1b1
0.4800910949707031
```

**Comment by schriftgestalt** [comment]
Good to know that this is fixed in Python3.

**Comment by justvanrossum** [comment]
> Good to know that this is fixed in Python3.

Or PyObjC... I can't verify that right now.

**Comment by justvanrossum** [comment]
@typemytype: if we do the same changes in DB, we may get a much better startup time in the 2.7 version.

**Comment by typemytype** [comment]
drawBot is not using any lazy import :) (also RF)
fe see https://github.com/typemytype/drawbot/blob/master/drawBot/drawBotDrawingTools.py#L3

personally I prefer to have `import AppKit` and `AppKit.NSObject....` but this is a personal flavour I guess... and lots more work to change in a PR

**Comment by justvanrossum** [comment]
@typemytype 

> drawBot is not using any lazy import :) (also RF)

I challenge you to search for `from AppKit` in the DB code base :)

**Comment by schriftgestalt** [comment]
I have done most of the changes in (my branch of) drawbot already. I check if I can port that.

**Comment by justvanrossum** [comment]
Ah DB PR would sure be great!

**Comment by typemytype** [comment]
:) oh https://github.com/typemytype/drawbot/search?utf8=✓&q=%22from+AppKit+import+*%22&type=

but those aren't used when DB is used as a module...

**Comment by justvanrossum** [comment]
> but those aren't used when DB is used as a module...

Don't you agree that the startup time of DB.app is rather, uhm, suboptimal? On 2.7 at least. On Python 3 it is just fine.

**Comment by typemytype** [comment]
that would idd explain the difference :)

**Comment by justvanrossum** [comment]
Exactly.

**Pull request merged**
